In [1]:
import pandas as pd

In [2]:
base_train = pd.read_csv('train_total_stratified.csv')
base_test = pd.read_csv('test_total_stratified.csv')
nova_base = pd.concat([base_train,base_test])
nova_base.drop(columns="Unnamed: 0", axis=1,inplace=True)
print(len(nova_base))
nova_base.drop_duplicates(subset='text', keep='first', inplace=True)
nova_base.drop_duplicates(subset='index_banco', keep='first', inplace=True)
print(len(nova_base))

nova_base.head()

2385
2355

,index_banco,datetime,username,text,ae,pc,pop
0,431,2022-08-24 22:34:16 utc,jairbolsonaro,"- sob comando do pt, o brasil atuava como mina...",1,1,1
1,604,2022-07-18 13:06:31 utc,jairbolsonaro,- ciente de que o desemprego traria ainda mais...,1,1,1
2,1367,2022-02-09 23:17:13 utc,jairbolsonaro,"- assim, reitero todo nosso apoio ao povo jude...",1,1,1
3,2293,2020-09-29 12:15:04 utc,jairbolsonaro,5- os responsáveis pela destruição de milhões ...,1,1,1
4,3169,2020-02-06 09:50:02 utc,jairbolsonaro,4- nossa economia está em plena recuperação. o...,1,1,1

In [4]:
nova_base.groupby(['ae', 'pc', 'pop']).size().reset_index(name='contagem')

   ae  pc  pop  contagem
0   0   0    0      1887
1   0   1    0       150
2   1   0    0       196
3   1   1    1       122

In [5]:
sample_teste = nova_base.sample(520,random_state=57)
sample_teste.groupby(['ae', 'pc', 'pop']).size().reset_index(name='contagem')

   ae  pc  pop  contagem
0   0   0    0       412
1   0   1    0        39
2   1   0    0        42
3   1   1    1        27

In [6]:
sample_treino = nova_base[~nova_base["index_banco"].isin(sample_teste["index_banco"])]
sample_treino.groupby(['ae', 'pc', 'pop']).size().reset_index(name='contagem')

   ae  pc  pop  contagem
0   0   0    0      1475
1   0   1    0       111
2   1   0    0       154
3   1   1    1        95

In [7]:
print(len(sample_teste) + len(sample_treino))
print(sum(sample_treino['text'].isin(sample_teste['text'])))

#sample_teste.to_csv('test_total_stratified v2.csv',index=False)
#sample_treino.to_csv('train_total_stratified v2.csv',index=False)

2355
0

In [8]:
filtro = (sample_treino['pop'] == 0) & (sample_treino['ae'] == 0) & (sample_treino['pc'] == 0)
selecionados_class0  = sample_treino[filtro].sample(720, random_state=22)
filtro2 = (sample_treino['pop'] == 1) | (sample_treino['ae'] == 1) | (sample_treino['pc'] == 1)


selecionados_class1 = sample_treino[filtro2]

In [9]:
subamostragem = pd.concat([selecionados_class0,selecionados_class1])
#subamostragem.to_csv('train_sub_stratified v2.csv',index=False)

In [11]:
len(subamostragem)

900

In [10]:
filtro = (sample_treino['pop'] == 0) & (sample_treino['ae'] == 0) & (sample_treino['pc'] == 0)
selecionados_class0  = sample_treino[filtro].sample(540, random_state=22)
filtro2 = (sample_treino['pop'] == 1) | (sample_treino['ae'] == 1) | (sample_treino['pc'] == 1)


selecionados_class1 = sample_treino[filtro2]
subamostragem = pd.concat([selecionados_class0,selecionados_class1])
#subamostragem.to_csv('train_sub_sub_stratified v2.csv',index=False)

In [11]:
subamostragem.groupby(['ae', 'pc', 'pop']).size().reset_index(name='contagem')

   ae  pc  pop  contagem
0   0   0    0       540
1   0   1    0       111
2   1   0    0       154
3   1   1    1        95